language: node_js
node_js:
  - "8.2.1"
services:
  - postgresql
before_script:
  # Postgres Setup
  - psql -c 'create database "wpt-ui-test";' -U postgres
  - DATABASE_URL=postgres://postgres:password@localhost:5432/wpt-ui-test
  # NPM setup
  - npm i
script:
  - npm t
